//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VM.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be in range [0x0000, 0x10000]..
        /// </summary>
        internal static string Memory_InvalidSizeMessage {
            get {
                return ResourceManager.GetString("Memory_InvalidSizeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected register.
        /// </summary>
        internal static string Parser_ExpectedRegisterMessage {
            get {
                return ResourceManager.GetString("Parser_ExpectedRegisterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected U16 or label name.
        /// </summary>
        internal static string Parser_InvalidJumpTargetMessage {
            get {
                return ResourceManager.GetString("Parser_InvalidJumpTargetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing digits for hex value.
        /// </summary>
        internal static string Scanner_HexMissingDigitsMessage {
            get {
                return ResourceManager.GetString("Scanner_HexMissingDigitsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid leading &apos;0&apos;.
        /// </summary>
        internal static string Scanner_InvalidLeadingZeroMessage {
            get {
                return ResourceManager.GetString("Scanner_InvalidLeadingZeroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value was too large for U16.
        /// </summary>
        internal static string Scanner_U16OverflowMessage {
            get {
                return ResourceManager.GetString("Scanner_U16OverflowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In base frame, nothing to return to..
        /// </summary>
        internal static string Stack_BaseFrameReturnMessage {
            get {
                return ResourceManager.GetString("Stack_BaseFrameReturnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack frame is empty..
        /// </summary>
        internal static string Stack_EmptyFrameMessage {
            get {
                return ResourceManager.GetString("Stack_EmptyFrameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack is full..
        /// </summary>
        internal static string Stack_FullMessage {
            get {
                return ResourceManager.GetString("Stack_FullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Address must be less than End Address..
        /// </summary>
        internal static string Stack_InvalidStartAddressMessage {
            get {
                return ResourceManager.GetString("Stack_InvalidStartAddressMessage", resourceCulture);
            }
        }
    }
}
